### ISSUE TITLE
آخرین نسخه

### ISSUE THREAD

**Issue by shahram7** [Mr30nama/30namaAndroidTV#2]
سلام و درود، چرا بعد از دانلود آخرین نسخه از صفحه گیت هاب و نصب اون باید پیام بگیریم که نسخه جدید در حال دانلود میباشد؟ چرا آخرین نسخه رو اینجا قرار نمی‌دید؟

**Comment by DevineDecrypter** [comment]
سلام،
این نسخه دیگه پشتیبانی نمیشه، لطفا ازین ریپو استفاده کنید
https://github.com/Mr30nama/30nama-Android-TV
